<?php defined('BASEPATH') OR exit('No direct script access allowed');

$config = [
	'table_open'				=> '<div class="table-responsive"><table class="table">',
	'heading_row_start'			=> '',
	'heading_previous_cell'		=> '<th><a href="{previous_url}">&lt;&lt;</a></th>',
	'heading_title_cell'		=> '',
	'heading_next_cell'			=> '<th><a href="{next_url}">&gt;&gt;</a></th>',
	'heading_row_end'			=> '',
	'week_row_start'			=> '',
	'week_day_cell'				=> '',
	'week_row_end'				=> '',
	'cal_row_start'				=> '<tr>',
	'cal_cell_start'			=> '<td>',
	'cal_cell_start_today'		=> '<td>',
	'cal_cell_start_other'		=> '<td">',
	'cal_cell_content'			=> '<a href="{content}">{day}</a>',
	'cal_cell_content_today'	=> '<a href="{content}"><strong>{day}</strong></a>',
	'cal_cell_no_content'		=> '{day}',
	'cal_cell_no_content_today'	=> '<strong>{day}</strong>',
	'cal_cell_blank'			=> '&nbsp;',
	'cal_cell_other'			=> '{day}',
	'cal_cell_end'				=> '</td>',
	'cal_cell_end_today'		=> '</td>',
	'cal_cell_end_other'		=> '</td>',
	'cal_row_end'				=> '</tr>',
	'table_close'				=> '</table></div>',
	'start_day'    				=> 'monday',
];